// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SignalMonitoring.API.Persistence;

namespace SignalMonitoring.API.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20200604020218_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SignalMonitoring.API.Persistence.SignalDataModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccessCode");

                    b.Property<string>("Area");

                    b.Property<string>("CustomerName");

                    b.Property<string>("Description");

                    b.Property<DateTime>("SingalDate");

                    b.Property<string>("Zone");

                    b.HasKey("id");

                    b.ToTable("Signals");
                });
#pragma warning restore 612, 618
        }
    }
}
